name: Python Application CI

on:
  push:
    branches: [ "master", "main", "develop" ]
  pull_request:
    branches: [ "master", "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black ruff pytest # Ensure dev dependencies for linting/testing are installed

    - name: Lint with Ruff
      run: |
        ruff check .

    - name: Format with Black (check only)
      run: |
        black --check .

    - name: Test with pytest
      run: |
        pytest 